### ISSUE TITLE
How to use Slime instead of .leex in LiveView?

### ISSUE THREAD

**Issue by owenstrevor** [slime-lang/phoenix_slime#71]
I see #61 and #63 #64 

But I still have no clue if I can use .slime to replace .leex and how to set it up?

I tried just using slime but the app won't compile :)

**Comment by owenstrevor** [comment]
I think I got it

Might not be right but, instead of

```
def render(assigns) do
  TaskView.render("tasks.html", assigns)
end
```

Just do

```
def render(assigns) do
  ~L"""
  <%= TaskView.render("tasks.html", assigns) %>
  """
end
```

Works for me.

**Comment by doomspork** [comment]
@owenstrevor I haven't had the chance to explore Slime + LiveView yet but I'd welcome any information you've learned. This is definitely something we want to support 😁

**Comment by cheerfulstoic** [comment]
@owenstrevor I tried your solution and it seems to function, but for when I look at the socket traffic it's re-rendering the whole template each time something changes, rather than just the parts that changes.  Is that what you're seeing?

I *think* that the problem is that it's got to be "live" rendering all the way down, including calling `live_render` instead of `render.  If you call `render` at any point it will just consider that entire template as the dynamic data and re-render it.  A pretty cool fallback behavior, but not fully efficient.

But you don't seem to be able to do `live_render` with `.html.slim` files yet.  I'm going to keep poking to see what I can find.

**Comment by cheerfulstoic** [comment]
An open question I don't know the answer to: I know that in Rails it supports having a sequence of extensions on views and works backwards.  So I would expect something like `.html.leex.slim` might work because it would see the `.slim` and turn it into a HTML or an EEX template, then if it's an EEX template it could see the `.leex` and interpret the EEX template as normal.  But if I were to guess, I would say even if phoenix did work backward on extensions like this that `.slim` files don't actually produce EEX templates but rather rendered HTML...

**Comment by cheerfulstoic** [comment]
Proof of concept that seems to be working so far (just stuck in `config/config.exs` for now):

```elixir
defmodule PhoenixSlime.LiveViewEngine do
  @behaviour Phoenix.Template.Engine

  @doc """
  Precompiles the String file_path into a function definition
  """
  def compile(path, _name) do
    path
    |> read!
    |> EEx.compile_string(engine: Phoenix.LiveView.Engine, file: path, line: 1)
  end

  defp read!(file_path) do
    file_path
    |> File.read!()
    |> Slime.Renderer.precompile()
  end
end

config :phoenix, :template_engines,
  slim: PhoenixSlime.Engine,
  slime: PhoenixSlime.Engine,
  slimleex: PhoenixSlime.LiveViewEngine
```

Just copied from [lib/phoenix_slime/engine.ex](https://github.com/slime-lang/phoenix_slime/blob/master/lib/phoenix_slime/engine.ex) and changed out the `engine` argument.

I could see having a `LiveViewEngine` in the `phoenix_slime` package, but perhaps there would be a simpler way with a way to pass an `engine` argument in to simply switch the `engine` option for `EEx.compile_string` but to default to `Phoenix.HTML.Engine`

**Comment by doomspork** [comment]
@cheerfulstoic I would _love_ if you'd open a PR with a new LiveViewEngine!

**Comment by cheerfulstoic** [comment]
👍 Done.  I was holding off because it didn't seem to be fully working as far as sending down only the dynamic bits that have changed in sub-templates.  But probably more important to get it working for people first ;p

**Comment by owenstrevor** [comment]
Great work @cheerfulstoic @doomspork, any docs on how to use this in the `task_live.ex`?

Here's what I'm guessing, after updating to the master branch, update `config.exs`
```
config :phoenix, :template_engines,
  slim: PhoenixSlime.Engine,
  slime: PhoenixSlime.Engine,
  slimleex: PhoenixSlime.LiveViewEngine
```

Then just name the file `tasks.html.slimleex`?

Then in the `task_live.ex` can change the render function from:
```
def render(assigns) do
  ~L"""
  <%= TaskView.render("tasks.html", assigns) %>
  """
end
```
To
```
def render(assigns) do
  TaskView.render("tasks.html", assigns)
end
```

My understanding is that the the PhoenixSlime.LiveViewEngine compiles the file into leex instead of into eex?

**Comment by cheerfulstoic** [comment]
Hey @owenstrevor .  That's kind of right, though really if you use a `PhoenixSlime.LiveViewEngine` (by creating a file with the extension `slimeex`) then `phoenix_slime` just switches from using [`Phoenix.HTML.Engine`](https://github.com/slime-lang/phoenix_slime/blob/master/lib/phoenix_slime/engine.ex#L10) to [`Phoenix.LiveView.Engine`](https://github.com/slime-lang/phoenix_slime/blob/master/lib/phoenix_slime/live_view_engine.ex#L10).  I think that that engine is what is used to render the `leex` files.  But this change doesn't effect the `~L` sigil (I think I saw a change for that somewhere else...)

**Comment by mxrguspxrt** [comment]
Why this task is closed? Why documentation has no info?

**Comment by rjurado01** [comment]
@mxrguspxrt You have to add `slimleex: PhoenixSlime.LiveViewEngine` to config templates as you can see on [README / Usage](https://github.com/slime-lang/phoenix_slime#usage) and change extension to `.slimleex` as you can see on @owenstrevor comment.

**Comment by doomspork** [comment]
Thank you @rjurado01 :purple_heart:
